# Generated by Django 5.1.6 on 2025-03-05 05:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='Enter Property Name', max_length=100)),
                ('type', models.CharField(choices=[('Residential', 'Residential'), ('Commercial', 'Commercial')], default='Residential', max_length=100)),
                ('area', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Area in sqft')),
                ('address', models.TextField(default='Enter Address', max_length=300)),
                ('state', models.CharField(default='Enter State', max_length=100)),
                ('owner', models.CharField(max_length=100)),
                ('owner_contact', models.IntegerField(default=0)),
                ('owner_email', models.EmailField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='static/images/')),
                ('units', models.IntegerField(default=1)),
                ('description', models.TextField(default='Enter Description', max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Property_Unit',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='Enter the Unit Name', max_length=100)),
                ('number_of_rooms', models.IntegerField(default=1)),
                ('number_of_bathrooms', models.IntegerField(default=1)),
                ('rent', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Price in INR')),
                ('furnished', models.BooleanField(default=False)),
                ('description', models.TextField(default='Enter Description', max_length=300)),
                ('availablity', models.CharField(choices=[('Available', 'Available'), ('Leased', 'Leased')], default='Available', max_length=100)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RealEstate.property')),
            ],
        ),
        migrations.CreateModel(
            name='Lease_Agreement',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('duration', models.IntegerField(default=1, verbose_name='Duration in months')),
                ('rent', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Rent in INR')),
                ('security_deposit', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Security Deposit in INR')),
                ('late_payment_penalty', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Penalty in INR')),
                ('payment_date', models.DateField(verbose_name='Payment Date every month')),
                ('payment_grace_period', models.IntegerField(default=0, verbose_name='Grace Period in days')),
                ('owner', models.CharField(max_length=100)),
                ('tenant', models.CharField(max_length=100)),
                ('owner_contact', models.IntegerField(default=0)),
                ('tenant_contact', models.IntegerField(default=0)),
                ('owner_email', models.EmailField(max_length=100)),
                ('tenant_email', models.EmailField(max_length=100)),
                ('description', models.TextField(default='Enter Description', max_length=300)),
                ('unit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='RealEstate.property_unit')),
            ],
        ),
    ]
