# Generated by Django 5.1.6 on 2025-03-07 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RealEstate', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
