# Generated by Django 5.1.6 on 2025-03-01 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RealEstate', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='property_owner_contact',
            field=models.IntegerField(default=0),
        ),
    ]
