# Generated by Django 5.1.6 on 2025-03-01 18:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RealEstate', '0002_alter_property_property_owner_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='property_furnished',
        ),
        migrations.RemoveField(
            model_name='property',
            name='property_price',
        ),
        migrations.RemoveField(
            model_name='property',
            name='property_status',
        ),
        migrations.CreateModel(
            name='Property_Unit',
            fields=[
                ('unit_id', models.AutoField(primary_key=True, serialize=False)),
                ('unit_name', models.CharField(default='Enter the Unit Name', max_length=100)),
                ('number_of_rooms', models.IntegerField(default=1)),
                ('number_of_bathrooms', models.IntegerField(default=1)),
                ('unit_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Price in INR')),
                ('unit_furnished', models.BooleanField(default=False)),
                ('unit_description', models.TextField(default='Enter Description', max_length=300)),
                ('unit_availablity', models.CharField(choices=[('Available', 'Available'), ('Sold', 'Sold')], default='Available', max_length=100)),
                ('property_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RealEstate.property')),
            ],
        ),
        migrations.CreateModel(
            name='Lease_Agreement',
            fields=[
                ('agreement_id', models.AutoField(primary_key=True, serialize=False)),
                ('agreement_start_date', models.DateField()),
                ('agreement_end_date', models.DateField()),
                ('agreement_duration', models.IntegerField(default=1, verbose_name='Duration in months')),
                ('agreement_rent', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Rent in INR')),
                ('agreement_security_deposit', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Security Deposit in INR')),
                ('late_payment_penalty', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Penalty in INR')),
                ('payment_date', models.DateField(verbose_name='Payment Date every month')),
                ('payment_grace_period', models.IntegerField(default=0, verbose_name='Grace Period in days')),
                ('agreement_termination', models.BooleanField(default=False)),
                ('agreement_termination_date', models.DateField(blank=True, null=True)),
                ('owner', models.CharField(max_length=100)),
                ('tenant', models.CharField(max_length=100)),
                ('owner_contact', models.IntegerField(default=0)),
                ('tenant_contact', models.IntegerField(default=0)),
                ('owner_email', models.EmailField(max_length=100)),
                ('tenant_email', models.EmailField(max_length=100)),
                ('agreement_description', models.TextField(default='Enter Description', max_length=300)),
                ('unit_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='RealEstate.property_unit')),
            ],
        ),
    ]
