# Generated by Django 5.1.6 on 2025-03-03 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RealEstate', '0003_remove_property_property_furnished_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='property_image',
            field=models.ImageField(blank=True, null=True, upload_to='static/images/'),
        ),
        migrations.AlterField(
            model_name='property_unit',
            name='unit_availablity',
            field=models.CharField(choices=[('Available', 'Available'), ('Leased', 'Leased')], default='Available', max_length=100),
        ),
    ]
