# Generated by Django 5.1.6 on 2025-03-03 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RealEstate', '0004_alter_property_property_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lease_agreement',
            name='agreement_termination',
        ),
        migrations.RemoveField(
            model_name='lease_agreement',
            name='agreement_termination_date',
        ),
    ]
