# Generated by Django 5.1.7 on 2025-03-13 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_remove_userpayment_has_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpayment',
            name='has_paid',
            field=models.BooleanField(default=False),
        ),
    ]
